# Site settings
title: DALI 2015 - Data Learning and Inference
venue:
permalink: "/:categories/:title.html"
conference:
  hosts:
  organizers:
  - name: Zoubin Ghaharamani
    url: "http://mlg.eng.cam.ac.uk/zoubin/"
    institute: University of Cambridge
  - name: Thomas Hoffman
    url: "http://www.da.inf.ethz.ch/people/ThomasHofmann/"
    institute: ETH Zurich
  - name: Neil Lawrence
    url: "http://inverseprobability.com"
    institute: University of Sheffield
  - name: Bernhard Schölkopf
    url: "http://ei.is.tuebingen.mpg.de/person/bs"
    institute: MPI Tübingen
  name: DALI 2015 - Data Learning and Inference
  location: La Palma (Canaries, Spain)
  year: 2015
  month: April
  dates:
  - {date: 10, day: Friday, month: April, year: 2015}
  - {date: 11, day: Saturday, month: April, year: 2015}
  - {date: 12, day: Sunday, month: April, year: 2015}
  draft: N # set to Y if the programme is draft only.
  fundraising:
  - name: Joaquin Quiñonero Candela
    url: http://quinonero.net/
    institute: Facebook
  sponsors:
  - name: Max-Planck-ETH Center for Learning Systems
baseurl: "/dali2015/" # the subpath of your site, e.g. /blog/
url: "http://dalimeeting.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  dalimeeting

# Build settings
markdown: kramdown
