# Site settings
title: DALI 2015 - Data Learning and Inference
banner: DSC015811.jpeg
permalink: "/:categories/:title.html"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
style: dali

baseurl: "/dali2015" # the subpath of your site, e.g. /blog/
url: "http://dalimeeting.org" # the base hostname & protocol for your site
twitter_username: 
github_username:  dalimeeting
author:
  name: DALI
  
ghub:
  edit: true
  repository: dali2015

conference:
  instance: 1st
  full_name: Data Learning and Inference
  name: Data Learning and Inference
  short_name: DALI
  location: La Palma, Canary Islands, Spain
  year: 2015
  venue: Hotel H10 Taburiente Playa
  venue_url: http://www.hotelh10taburienteplaya.com/en/index.html
  hosts:
  organizers:
  - family: Ghaharamani
    given: Zoubin
    url: "http://mlg.eng.cam.ac.uk/zoubin/"
    institute: University of Cambridge
  - given: Thomas 
    family: Hoffman
    url: "http://www.da.inf.ethz.ch/people/ThomasHofmann/"
    institute: ETH Zurich
  - given: Neil D.
    family: Lawrence
    url: "http://inverseprobability.com"
    institute: University of Sheffield
  - given: Bernhard 
    family: Schölkopf
    url: "http://ei.is.tuebingen.mpg.de/person/bs"
    institute: MPI Tübingen
  month: April
  dates:
  - 2015-04-10
  - 2015-04-11
  - 2015-04-12
  draft: false # set to true if the programme is draft only.
  fundraising:
  - given: Joaquin 
    family: Quiñonero Candela
    url: http://quinonero.net/
    institute: Facebook
  sponsors:
  - name: Max-Planck-ETH Center for Learning Systems
  - name: Facebook


# Build settings
markdown: kramdown
